package com.entando.apiman.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.client.WebClient;

@Configuration
public class WebClientConfiguration {
    @Bean
    public WebClient webclient() {
      String token ="eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE2NjE4NDE5NjQsImlhdCI6MTY2MTg0MTcyNCwiYXV0aF90aW1lIjoxNjYxODM4MzU1LCJqdGkiOiJjM2ViNGQyZC00MmQwLTRlMDktODU5ZS1jZTJkZjllMGI2ZmUiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvYXBpbWFuIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjYwZDljMWM2LTc1ODEtNDliNC1hNWJlLWU1YTRmOGYyMDhlOSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwaW1hbnVpIiwic2Vzc2lvbl9zdGF0ZSI6ImJkMTk2MGExLTM4MzQtNGQzNS05MmFhLTk2OTkwZTgyYmNjNSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ0MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJiZDE5NjBhMS0zODM0LTRkMzUtOTJhYS05Njk5MGU4MmJjYzUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJHb3ZpbmQgVGVzdCIsInByZWZlcnJlZF91c2VybmFtZSI6ImdvdmluZCIsImdpdmVuX25hbWUiOiJHb3ZpbmQiLCJmYW1pbHlfbmFtZSI6IlRlc3QiLCJlbWFpbCI6ImdvdmluZDM0QDEyMyJ9.SB6FakILcbbcvx6YYUcKuvqKI8UOQ0LgEquD6z6Ddg6FFhZO95X39a94hox3KilyY5duBr1-ls7tJDmxymu3FBoSZdm7mEYijfiwud9HlOrN5LedDHQ_9gTPC5BgsoE_G9JhUuxOp0_w-yIxtRB6EKrWHcWnKLUFgiA1mAWw7n8"
      		+ "  \"refreshPeriod";
        WebClient webClient = WebClient
                .builder()
                .baseUrl("http://localhost:8080")
                .defaultCookie("cookieKey", "cookieValue")
                //  .defaultHeaders(header -> header.setBasicAuth(userName, password))
                //.defaultHeaders(header -> header.setBearerAuth(""))
                .defaultHeaders(header -> header.setBearerAuth("eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJGSjg2R2NGM2pUYk5MT2NvNE52WmtVQ0lVbWZZQ3FvcXRPUWVNZmJoTmxFIn0.eyJleHAiOjE2NjIwMjY3MTUsImlhdCI6MTY2MjAyNjQ3NSwiYXV0aF90aW1lIjoxNjYyMDA3NDU1LCJqdGkiOiI1YzgzNWIwMi04YjAxLTRiYmItODM3Yy1lODMzY2JlOTk4NzIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAvYXV0aC9yZWFsbXMvYXBpbWFuIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjYwZDljMWM2LTc1ODEtNDliNC1hNWJlLWU1YTRmOGYyMDhlOSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFwaW1hbnVpIiwic2Vzc2lvbl9zdGF0ZSI6ImM4ZmNkYjRiLWMzNWQtNDI3NS05YTFlLTJjNGE1OTY0YmQwNCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvY2FsaG9zdDo4MDgwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6ODQ0MyJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImFwaXVzZXIiLCJkZWZhdWx0LXJvbGVzLWFwaW1hbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzaWQiOiJjOGZjZGI0Yi1jMzVkLTQyNzUtOWExZS0yYzRhNTk2NGJkMDQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJHb3ZpbmQgVGVzdCIsInByZWZlcnJlZF91c2VybmFtZSI6ImdvdmluZCIsImdpdmVuX25hbWUiOiJHb3ZpbmQiLCJmYW1pbHlfbmFtZSI6IlRlc3QiLCJlbWFpbCI6ImdvdmluZDM0QDEyMyJ9.V9iKNATqT9eXAmCBvhr9HW33mVGdju6p7O0dFGC_jxPhmc6tOdr-b2-QmGhUQ4t77aQTSab9sXmqe5QOu4BG4HL0v9biv4kdIhbteyWl-S8Lyxy3PzeYD8oOAtuyf2EtGGbJf9l7lRkfJYQffoWKXuKzekecBqB2fDS7vdMuH8c"))
                .build();
        return webClient;
    }

}